import {
  resolveSupabaseKeepaliveEnv,
  runSupabaseKeepalive,
  type SupabaseKeepaliveEnv,
} from "./lib/cloudflare/supabase-keepalive";

// @ts-ignore -- generated by `npx @opennextjs/cloudflare build`
import openNextWorker from "./.open-next/worker.js";
// @ts-ignore -- generated by `npx @opennextjs/cloudflare build`
import * as generatedNextEnv from "./.open-next/cloudflare/next-env.mjs";
// @ts-ignore -- generated by `npx @opennextjs/cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException?(): void;
};

type WorkerScheduledController = {
  cron: string;
  scheduledTime: number;
  noRetry?(): void;
};

type WorkerEnv = SupabaseKeepaliveEnv & Record<string, unknown>;

async function handleSupabaseKeepalive(controller: WorkerScheduledController, env: WorkerEnv): Promise<void> {
  const scheduledAt = new Date(controller.scheduledTime).toISOString();
  const keepaliveEnv = resolveSupabaseKeepaliveEnv(env, generatedNextEnv);

  try {
    const result = await runSupabaseKeepalive(keepaliveEnv);
    console.log("[supabase-keepalive] ok", {
      cron: controller.cron,
      scheduledAt,
      status: result.status,
      url: result.url,
    });
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);

    if (
      detail.includes("NEXT_PUBLIC_SUPABASE_URL is missing")
      || detail.includes("NEXT_PUBLIC_SUPABASE_ANON_KEY is missing")
    ) {
      controller.noRetry?.();
    }

    console.error("[supabase-keepalive] failed", {
      cron: controller.cron,
      scheduledAt,
      error: detail,
    });
    throw error;
  }
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: WorkerExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(controller: WorkerScheduledController, env: WorkerEnv, ctx: WorkerExecutionContext): Promise<void> {
    ctx.waitUntil(handleSupabaseKeepalive(controller, env));
  },
};

export default worker;
