import type { Database } from "@/types/database";
import type { PipelineLog } from "@/types/pipeline";

type GameRow = Database["public"]["Tables"]["games_metadata"]["Row"];

const now = Date.now();
const minutes = (m: number) => new Date(now - m * 60_000).toISOString();

export const PREVIEW_GAMES: GameRow[] = [
  {
    id: "demo-neon-drift",
    slug: "neon-drift-outrun-chain",
    name: "Neon Drift: Outrun Chain",
    genre: "score-attack",
    url: "https://example.com/demo/neon-drift",
    thumbnail_url: "/assets/preview/neon-drift.svg",
    ai_review:
      "90초 생존 구간에서 드리프트 라인 유지와 근접 회피를 반복하는 리듬형 스코어어택입니다.\n부스트 게이지를 초반에 소모하지 말고 후반 교차 구간에서 사용하면 안정적으로 점수를 끌어올릴 수 있습니다.",
    screenshot_url: "/assets/preview/neon-drift.svg",
    status: "active",
    created_by: null,
    created_at: minutes(600),
    updated_at: minutes(20),
  },
  {
    id: "demo-skyline",
    slug: "skyline-jet-infinite",
    name: "풀3D 비행기 조종 시뮬레이터 Infinite",
    genre: "arcade",
    url: "https://example.com/demo/skyline",
    thumbnail_url: "/assets/preview/skyline-jet.svg",
    ai_review:
      "저고도 비행에서 장애물 간격을 읽는 시야 확보가 핵심입니다.\n스로틀을 일정하게 유지하면 초반 실패율이 크게 줄어듭니다.",
    screenshot_url: "/assets/preview/skyline-jet.svg",
    status: "active",
    created_by: null,
    created_at: minutes(420),
    updated_at: minutes(55),
  },
  {
    id: "demo-fracture",
    slug: "fracture-labyrinth-prototype",
    name: "Fracture Labyrinth Prototype",
    genre: "puzzle",
    url: "https://example.com/demo/fracture",
    thumbnail_url: "/assets/preview/fracture-labyrinth.svg",
    ai_review: "실험작: 시야 분할 퍼즐.\n정답보다 경로 탐색 순서가 핵심인 유형입니다.",
    screenshot_url: "/assets/preview/fracture-labyrinth.svg",
    status: "active",
    created_by: null,
    created_at: minutes(360),
    updated_at: minutes(120),
  },
  {
    id: "demo-ember",
    slug: "ember-survival-alpha",
    name: "Ember Survival Alpha",
    genre: "survival",
    url: "https://example.com/demo/ember",
    thumbnail_url: "/assets/preview/ember-survival.svg",
    ai_review: "초반 자원 루프 학습형 서바이벌 알파 버전입니다.",
    screenshot_url: "/assets/preview/ember-survival.svg",
    status: "active",
    created_by: null,
    created_at: minutes(300),
    updated_at: minutes(140),
  },
  {
    id: "demo-timebreak",
    slug: "timebreakers-open-beta",
    name: "Time Breakers Open Beta",
    genre: "arcade",
    url: "https://example.com/demo/timebreak",
    thumbnail_url: "/assets/preview/timebreakers.svg",
    ai_review: null,
    screenshot_url: "/assets/preview/timebreakers.svg",
    status: "inactive",
    created_by: null,
    created_at: minutes(260),
    updated_at: minutes(220),
  },
  {
    id: "demo-aether",
    slug: "aether-courier-lab",
    name: "Aether Courier Lab",
    genre: "score-attack",
    url: "https://example.com/demo/aether",
    thumbnail_url: "/assets/preview/aether-courier.svg",
    ai_review: "실험 루프 테스트용 빌드",
    screenshot_url: "/assets/preview/aether-courier.svg",
    status: "active",
    created_by: null,
    created_at: minutes(200),
    updated_at: minutes(30),
  },
];

export const PREVIEW_PIPELINE_LOGS: PipelineLog[] = [
  {
    id: 1,
    pipeline_id: "demo-pipeline-01",
    stage: "report",
    status: "success",
    agent_name: "reporter",
    message: "Launch note posted to channel and dashboard card updated.",
    reason: null,
    attempt: 1,
    metadata: {},
    created_at: minutes(2),
  },
  {
    id: 2,
    pipeline_id: "demo-pipeline-01",
    stage: "release",
    status: "success",
    agent_name: "releaser",
    message: "Artifact uploaded and archive manifest synchronized.",
    reason: null,
    attempt: 1,
    metadata: {},
    created_at: minutes(4),
  },
  {
    id: 3,
    pipeline_id: "demo-pipeline-01",
    stage: "qa_quality",
    status: "success",
    agent_name: "qa_quality",
    message: "Playwright smoke and quality gate passed.",
    reason: null,
    attempt: 1,
    metadata: { non_fatal_warnings: ["minor contrast warning"] },
    created_at: minutes(6),
  },
  {
    id: 4,
    pipeline_id: "demo-pipeline-01",
    stage: "build",
    status: "running",
    agent_name: "developer",
    message: "Packaging WebGL bundle and generating release assets.",
    reason: null,
    attempt: 1,
    metadata: {},
    created_at: minutes(8),
  },
  {
    id: 5,
    pipeline_id: "demo-pipeline-01",
    stage: "design",
    status: "success",
    agent_name: "designer",
    message: "Visual token set and viewport-safe UI spec generated.",
    reason: null,
    attempt: 1,
    metadata: {},
    created_at: minutes(10),
  },
  {
    id: 6,
    pipeline_id: "demo-pipeline-01",
    stage: "plan",
    status: "success",
    agent_name: "planner",
    message: "Gameplay loop, risk matrix, and IA draft completed.",
    reason: null,
    attempt: 1,
    metadata: {},
    created_at: minutes(12),
  },
  {
    id: 7,
    pipeline_id: "demo-pipeline-01",
    stage: "analyze",
    status: "success",
    agent_name: "analyzer",
    message: "Keyword intake validated and mission started.",
    reason: null,
    attempt: 1,
    metadata: {},
    created_at: minutes(14),
  },
  {
    id: 8,
    pipeline_id: "demo-pipeline-02",
    stage: "qa_runtime",
    status: "error",
    agent_name: "qa_runtime",
    message: "Mobile HUD overlap detected on 390x844 viewport.",
    reason: "layout_overlap",
    attempt: 2,
    metadata: { fatal_errors: ["hud_overlap"] },
    created_at: minutes(18),
  },
];

export const PREVIEW_TOKEN_SUMMARY = {
  totalTokens: 39695,
  promptTokens: 8042,
  completionTokens: 4160,
  estimatedCostUsd: 0,
  flashPromptTokens: 3696,
  flashCompletionTokens: 2187,
  proPromptTokens: 4346,
  proCompletionTokens: 1973,
  unpricedTokens: 0,
  finalizedPipelines: 10,
  sampledPipelines: 0,
};

export const PREVIEW_TOKEN_ROWS = [
  {
    key: "demo-neon",
    name: "Neon Drift: Outrun Chain",
    slug: "neon-drift-outrun-chain",
    secondaryLabel: "neon-drift-outrun-chain",
    costSource: "finalized" as const,
    pipelineCount: 1,
    promptTokens: 874,
    completionTokens: 433,
    totalTokens: 4416,
    estimatedCostUsd: 0,
    lastSeenAt: minutes(20),
  },
  {
    key: "demo-skyline",
    name: "풀3D 비행기 조종 시뮬레이터 Infinite",
    slug: "skyline-jet-infinite",
    secondaryLabel: "skyline-jet-infinite",
    costSource: "finalized" as const,
    pipelineCount: 1,
    promptTokens: 810,
    completionTokens: 404,
    totalTokens: 4055,
    estimatedCostUsd: 0,
    lastSeenAt: minutes(55),
  },
  {
    key: "demo-fracture",
    name: "Fracture Labyrinth Prototype",
    slug: "fracture-labyrinth-prototype",
    secondaryLabel: "fracture-labyrinth-prototype",
    costSource: "sampled" as const,
    pipelineCount: 1,
    promptTokens: 620,
    completionTokens: 318,
    totalTokens: 938,
    estimatedCostUsd: 0,
    lastSeenAt: minutes(85),
  },
];

export function getPreviewGameById(id: string): GameRow | null {
  return PREVIEW_GAMES.find((game) => game.id === id) ?? null;
}
