import type { Database } from "@/types/database";

type GameRow = Database["public"]["Tables"]["games_metadata"]["Row"];

const now = Date.now();
const minutes = (m: number) => new Date(now - m * 60_000).toISOString();

export const PREVIEW_GAMES: GameRow[] = [
  {
    id: "demo-neon-drift",
    slug: "neon-drift-outrun-chain",
    name: "Neon Drift: Outrun Chain",
    genre: "score-attack",
    url: "https://example.com/demo/neon-drift",
    thumbnail_url: "/assets/preview/neon-drift.svg",
    ai_review:
      "90초 생존 구간에서 드리프트 라인 유지와 근접 회피를 반복하는 리듬형 스코어어택입니다.\n부스트 게이지를 초반에 소모하지 말고 후반 교차 구간에서 사용하면 안정적으로 점수를 끌어올릴 수 있습니다.",
    screenshot_url: "/assets/preview/neon-drift.svg",
    status: "active",
    created_by: null,
    created_at: minutes(600),
    updated_at: minutes(20),
  },
  {
    id: "demo-skyline",
    slug: "skyline-jet-infinite",
    name: "풀3D 비행기 조종 시뮬레이터 Infinite",
    genre: "arcade",
    url: "https://example.com/demo/skyline",
    thumbnail_url: "/assets/preview/skyline-jet.svg",
    ai_review:
      "저고도 비행에서 장애물 간격을 읽는 시야 확보가 핵심입니다.\n스로틀을 일정하게 유지하면 초반 실패율이 크게 줄어듭니다.",
    screenshot_url: "/assets/preview/skyline-jet.svg",
    status: "active",
    created_by: null,
    created_at: minutes(420),
    updated_at: minutes(55),
  },
  {
    id: "demo-fracture",
    slug: "fracture-labyrinth-prototype",
    name: "Fracture Labyrinth Prototype",
    genre: "puzzle",
    url: "https://example.com/demo/fracture",
    thumbnail_url: "/assets/preview/fracture-labyrinth.svg",
    ai_review: "실험작: 시야 분할 퍼즐.\n정답보다 경로 탐색 순서가 핵심인 유형입니다.",
    screenshot_url: "/assets/preview/fracture-labyrinth.svg",
    status: "active",
    created_by: null,
    created_at: minutes(360),
    updated_at: minutes(120),
  },
  {
    id: "demo-ember",
    slug: "ember-survival-alpha",
    name: "Ember Survival Alpha",
    genre: "survival",
    url: "https://example.com/demo/ember",
    thumbnail_url: "/assets/preview/ember-survival.svg",
    ai_review: "초반 자원 루프 학습형 서바이벌 알파 버전입니다.",
    screenshot_url: "/assets/preview/ember-survival.svg",
    status: "active",
    created_by: null,
    created_at: minutes(300),
    updated_at: minutes(140),
  },
  {
    id: "demo-timebreak",
    slug: "timebreakers-open-beta",
    name: "Time Breakers Open Beta",
    genre: "arcade",
    url: "https://example.com/demo/timebreak",
    thumbnail_url: "/assets/preview/timebreakers.svg",
    ai_review: null,
    screenshot_url: "/assets/preview/timebreakers.svg",
    status: "inactive",
    created_by: null,
    created_at: minutes(260),
    updated_at: minutes(220),
  },
  {
    id: "demo-aether",
    slug: "aether-courier-lab",
    name: "Aether Courier Lab",
    genre: "score-attack",
    url: "https://example.com/demo/aether",
    thumbnail_url: "/assets/preview/aether-courier.svg",
    ai_review: "실험 루프 테스트용 빌드",
    screenshot_url: "/assets/preview/aether-courier.svg",
    status: "active",
    created_by: null,
    created_at: minutes(200),
    updated_at: minutes(30),
  },
];

export function getPreviewGameById(id: string): GameRow | null {
  return PREVIEW_GAMES.find((game) => game.id === id) ?? null;
}

export function getPreviewGameBySlug(slug: string): GameRow | null {
  return PREVIEW_GAMES.find((game) => game.slug === slug) ?? null;
}

export const PREVIEW_SESSIONS = [
  {
    session_id: "sess-demo-1",
    title: "Neon Drift Session",
    genre: "racing",
    status: "published",
    score: 86,
    created_at: minutes(40),
    updated_at: minutes(5),
  },
  {
    session_id: "sess-demo-2",
    title: "Skyline Jet Session",
    genre: "flight",
    status: "active",
    score: 74,
    created_at: minutes(30),
    updated_at: minutes(6),
  },
  {
    session_id: "sess-demo-3",
    title: "Fracture Lab Session",
    genre: "puzzle",
    status: "cancelled",
    score: 55,
    created_at: minutes(20),
    updated_at: minutes(8),
  },
] as const;

export const PREVIEW_SESSION_EVENTS: Record<string, Array<Record<string, unknown>>> = {
  "sess-demo-1": [
    {
      id: "se-1",
      session_id: "sess-demo-1",
      event_type: "agent_activity",
      agent: "codegen",
      action: "generate",
      summary: "Generated playable racing prototype",
      score: 70,
      before_score: 0,
      after_score: 70,
      decision_reason: "initial_user_prompt",
      input_signal: "retro outrun racing",
      change_impact: "initial_generation",
      confidence: 0.91,
      error_code: null,
      created_at: minutes(18),
    },
    {
      id: "se-2",
      session_id: "sess-demo-1",
      event_type: "agent_activity",
      agent: "visual_qa",
      action: "evaluate",
      summary: "HUD contrast improved for mobile",
      score: 84,
      before_score: 70,
      after_score: 84,
      decision_reason: "visual_metrics_assessment",
      input_signal: "genre=racing",
      change_impact: "quality_pass",
      confidence: 0.74,
      error_code: null,
      created_at: minutes(12),
    },
    {
      id: "se-3",
      session_id: "sess-demo-1",
      event_type: "publish_success",
      agent: "codegen",
      action: "publish",
      summary: "Published to /play/neon-drift-outrun-chain",
      score: 86,
      before_score: 84,
      after_score: 86,
      decision_reason: "user_requested_publish",
      input_signal: "publish",
      change_impact: "session_published",
      confidence: 1,
      error_code: null,
      created_at: minutes(5),
    },
  ],
  "sess-demo-2": [
    {
      id: "se-4",
      session_id: "sess-demo-2",
      event_type: "agent_activity",
      agent: "playtester",
      action: "test",
      summary: "Boot ok but collision recovery feels harsh",
      score: 62,
      before_score: 74,
      after_score: 68,
      decision_reason: "runtime_boot_and_console_validation",
      input_signal: "html_size=9021",
      change_impact: "runtime_issue_detected",
      confidence: 0.71,
      error_code: "runtime_tuning_needed",
      created_at: minutes(7),
    },
  ],
  "sess-demo-3": [
    {
      id: "se-5",
      session_id: "sess-demo-3",
      event_type: "session_cancelled",
      agent: null,
      action: "cancel",
      summary: "Session cancelled by operator",
      score: 0,
      before_score: 55,
      after_score: 55,
      decision_reason: "operator_requested_cancel",
      input_signal: "cancel",
      change_impact: "future_prompt_blocked",
      confidence: 1,
      error_code: null,
      created_at: minutes(8),
    },
  ],
};
