import type { Database } from "@/types/database";

type GameRow = Database["public"]["Tables"]["games_metadata"]["Row"];

const now = Date.now();
const minutes = (m: number) => new Date(now - m * 60_000).toISOString();

export const PREVIEW_CREATORS = {
  "creator-demo-1": {
    id: "creator-demo-1",
    alias: "creator-neon",
    headline: "레이싱과 속도감을 중심으로 프로토타입을 만드는 제작자",
  },
  "creator-demo-2": {
    id: "creator-demo-2",
    alias: "creator-sky",
    headline: "비행과 공간감이 있는 3D 플레이 경험을 실험하는 제작자",
  },
} as const;

export const PREVIEW_GAMES: GameRow[] = [
  {
    id: "demo-neon-drift",
    slug: "neon-drift-outrun-chain",
    name: "Neon Drift: Outrun Chain",
    genre: "score-attack",
    url: "https://example.com/demo/neon-drift",
    thumbnail_url: "/assets/preview/neon-drift.svg",
    ai_review:
      "90초 생존 구간에서 드리프트 라인 유지와 근접 회피를 반복하는 리듬형 스코어어택입니다.\n부스트 게이지를 초반에 소모하지 말고 후반 교차 구간에서 사용하면 안정적으로 점수를 끌어올릴 수 있습니다.",
    short_description: "네온 서킷에서 라인을 유지하며 기록을 줄여가는 하이스피드 레이싱",
    description:
      "Neon Drift: Outrun Chain\n\n네온 서킷에서 라인을 유지하며 기록을 줄여가는 하이스피드 레이싱 게임입니다.\n\n핵심 포인트\n- 체크포인트를 이어가며 랩타임을 줄입니다.\n- 코너 진입 전 감속, 탈출 구간 재가속이 핵심입니다.",
    genre_primary: "racing",
    genre_tags: ["racing", "3d", "time-attack", "neon"],
    hero_image_url: "/assets/preview/neon-drift.svg",
    featured_rank: 1,
    released_at: minutes(18),
    visibility: "public",
    play_count_cached: 248,
    marketing_summary: "네온 서킷에서 라인을 유지하며 기록을 줄여가는 하이스피드 레이싱",
    play_overview: [
      "체크포인트를 이어가며 랩타임을 줄이는 레이싱 빌드입니다.",
      "브레이킹 타이밍과 코너 탈출 가속이 핵심입니다.",
    ],
    controls_guide: [
      "조향: ← / → 또는 A / D",
      "가속/감속: ↑ / ↓ 또는 W / S",
      "재시작: R",
    ],
    publish_copy_version: "v1",
    screenshot_url: "/assets/preview/neon-drift.svg",
    status: "active",
    created_by: "creator-demo-1",
    created_at: minutes(600),
    updated_at: minutes(20),
  },
  {
    id: "demo-skyline",
    slug: "skyline-jet-infinite",
    name: "풀3D 비행기 조종 시뮬레이터 Infinite",
    genre: "arcade",
    url: "https://example.com/demo/skyline",
    thumbnail_url: "/assets/preview/skyline-jet.svg",
    ai_review:
      "저고도 비행에서 장애물 간격을 읽는 시야 확보가 핵심입니다.\n스로틀을 일정하게 유지하면 초반 실패율이 크게 줄어듭니다.",
    short_description: "우주 전장에서 추격과 회피를 반복하는 3D 플라이트 슈팅 경험",
    description:
      "풀3D 비행기 조종 시뮬레이터 Infinite\n\n우주 전장에서 추격과 회피를 반복하는 3D 플라이트 슈팅 경험을 제공합니다.\n\n핵심 포인트\n- 적 편대를 추격하며 전장을 크게 선회합니다.\n- 부스트와 자세 제어를 짧게 나눠 쓰는 것이 중요합니다.",
    genre_primary: "flight",
    genre_tags: ["flight", "3d", "dogfight", "arcade"],
    hero_image_url: "/assets/preview/skyline-jet.svg",
    featured_rank: 3,
    released_at: minutes(54),
    visibility: "public",
    play_count_cached: 146,
    marketing_summary: "우주 전장에서 추격과 회피를 반복하는 3D 플라이트 슈팅 경험",
    play_overview: [
      "적 편대를 추격하며 전장을 크게 선회하는 도그파이트형 전투입니다.",
      "부스트와 자세 제어를 짧게 나눠 쓰면 안정적으로 살아남을 수 있습니다.",
    ],
    controls_guide: [
      "피치/롤: W/S · A/D",
      "요/부스트: Q/E · Shift",
      "사격/재시작: 클릭 또는 Space · R",
    ],
    publish_copy_version: "v1",
    screenshot_url: "/assets/preview/skyline-jet.svg",
    status: "active",
    created_by: "creator-demo-2",
    created_at: minutes(420),
    updated_at: minutes(55),
  },
  {
    id: "demo-fracture",
    slug: "fracture-labyrinth-prototype",
    name: "Fracture Labyrinth Prototype",
    genre: "puzzle",
    url: "https://example.com/demo/fracture",
    thumbnail_url: "/assets/preview/fracture-labyrinth.svg",
    ai_review: "실험작: 시야 분할 퍼즐.\n정답보다 경로 탐색 순서가 핵심인 유형입니다.",
    short_description: "시야 분할과 경로 판단에 집중한 실험형 퍼즐 프로토타입",
    description:
      "Fracture Labyrinth Prototype\n\n시야 분할과 경로 판단에 집중한 실험형 퍼즐 프로토타입입니다.\n\n핵심 포인트\n- 분리된 시야 조각을 읽어 경로를 해석해야 합니다.\n- 정답보다 탐색 순서가 중요한 구조입니다.",
    genre_primary: "puzzle",
    genre_tags: ["puzzle", "prototype", "experimental"],
    hero_image_url: "/assets/preview/fracture-labyrinth.svg",
    featured_rank: 6,
    released_at: minutes(118),
    visibility: "public",
    play_count_cached: 52,
    marketing_summary: "시야 분할과 경로 판단에 집중한 실험형 퍼즐 프로토타입",
    play_overview: [
      "분리된 시야 조각을 읽어 경로를 순서대로 해석해야 합니다.",
      "정답보다 탐색 순서가 중요한 퍼즐입니다.",
    ],
    controls_guide: [
      "이동: 방향키 또는 WASD",
      "상호작용: Space",
      "재시작: R",
    ],
    publish_copy_version: "v1",
    screenshot_url: "/assets/preview/fracture-labyrinth.svg",
    status: "active",
    created_by: "creator-demo-2",
    created_at: minutes(360),
    updated_at: minutes(120),
  },
  {
    id: "demo-ember",
    slug: "ember-survival-alpha",
    name: "Ember Survival Alpha",
    genre: "survival",
    url: "https://example.com/demo/ember",
    thumbnail_url: "/assets/preview/ember-survival.svg",
    ai_review: "초반 자원 루프 학습형 서바이벌 알파 버전입니다.",
    short_description: "초반 자원 루프를 익히며 생존 시간을 늘려가는 서바이벌 알파",
    description:
      "Ember Survival Alpha\n\n초반 자원 루프를 익히며 생존 시간을 늘려가는 서바이벌 알파 버전입니다.\n\n핵심 포인트\n- 생존 루프를 빠르게 익혀야 합니다.\n- 압박이 커지기 전에 위치를 정리하는 것이 중요합니다.",
    genre_primary: "survival",
    genre_tags: ["survival", "alpha", "arcade"],
    hero_image_url: "/assets/preview/ember-survival.svg",
    featured_rank: 4,
    released_at: minutes(138),
    visibility: "public",
    play_count_cached: 94,
    marketing_summary: "초반 자원 루프를 익히며 생존 시간을 늘려가는 서바이벌 알파",
    play_overview: [
      "생존 루프를 빠르게 익히고 압박이 커지기 전에 위치를 정리하세요.",
    ],
    controls_guide: [
      "이동: 방향키 또는 WASD",
      "액션: Space",
      "재시작: R",
    ],
    publish_copy_version: "v1",
    screenshot_url: "/assets/preview/ember-survival.svg",
    status: "active",
    created_by: "creator-demo-1",
    created_at: minutes(300),
    updated_at: minutes(140),
  },
  {
    id: "demo-timebreak",
    slug: "timebreakers-open-beta",
    name: "Time Breakers Open Beta",
    genre: "arcade",
    url: "https://example.com/demo/timebreak",
    thumbnail_url: "/assets/preview/timebreakers.svg",
    ai_review: null,
    short_description: null,
    description: null,
    genre_primary: "arcade",
    genre_tags: ["arcade", "beta"],
    hero_image_url: "/assets/preview/timebreakers.svg",
    featured_rank: null,
    released_at: minutes(210),
    visibility: "hidden",
    play_count_cached: 0,
    marketing_summary: null,
    play_overview: [],
    controls_guide: [],
    publish_copy_version: null,
    screenshot_url: "/assets/preview/timebreakers.svg",
    status: "inactive",
    created_by: "creator-demo-2",
    created_at: minutes(260),
    updated_at: minutes(220),
  },
  {
    id: "demo-aether",
    slug: "aether-courier-lab",
    name: "Aether Courier Lab",
    genre: "score-attack",
    url: "https://example.com/demo/aether",
    thumbnail_url: "/assets/preview/aether-courier.svg",
    ai_review: "실험 루프 테스트용 빌드",
    short_description: "실험 루프와 이동 감각을 테스트하는 프로토타입 빌드",
    description:
      "Aether Courier Lab\n\n실험 루프와 이동 감각을 테스트하는 프로토타입 빌드입니다.\n\n핵심 포인트\n- 핵심 루프 검증에 집중한 테스트 빌드입니다.\n- 이동 감각과 템포를 빠르게 점검할 수 있습니다.",
    genre_primary: "score-attack",
    genre_tags: ["score-attack", "prototype", "flight"],
    hero_image_url: "/assets/preview/aether-courier.svg",
    featured_rank: 2,
    released_at: minutes(28),
    visibility: "public",
    play_count_cached: 182,
    marketing_summary: "실험 루프와 이동 감각을 테스트하는 프로토타입 빌드",
    play_overview: [
      "핵심 루프와 이동 감각 검증에 집중한 테스트 빌드입니다.",
    ],
    controls_guide: [
      "이동: 방향키 또는 WASD",
      "액션: Space",
      "재시작: R",
    ],
    publish_copy_version: "v1",
    screenshot_url: "/assets/preview/aether-courier.svg",
    status: "active",
    created_by: "creator-demo-1",
    created_at: minutes(200),
    updated_at: minutes(30),
  },
];

export function getPreviewGameById(id: string): GameRow | null {
  return PREVIEW_GAMES.find((game) => game.id === id) ?? null;
}

export function getPreviewGameBySlug(slug: string): GameRow | null {
  return PREVIEW_GAMES.find((game) => game.slug === slug) ?? null;
}

export const PREVIEW_SESSIONS = [
  {
    session_id: "sess-demo-1",
    title: "Neon Drift Session",
    genre: "racing",
    status: "published",
    score: 86,
    created_at: minutes(40),
    updated_at: minutes(5),
  },
  {
    session_id: "sess-demo-2",
    title: "Skyline Jet Session",
    genre: "flight",
    status: "active",
    score: 74,
    created_at: minutes(30),
    updated_at: minutes(6),
  },
  {
    session_id: "sess-demo-3",
    title: "Fracture Lab Session",
    genre: "puzzle",
    status: "cancelled",
    score: 55,
    created_at: minutes(20),
    updated_at: minutes(8),
  },
] as const;

export const PREVIEW_SESSION_EVENTS: Record<string, Array<Record<string, unknown>>> = {
  "sess-demo-1": [
    {
      id: "se-1",
      session_id: "sess-demo-1",
      event_type: "agent_activity",
      agent: "codegen",
      action: "generate",
      summary: "Generated playable racing prototype",
      score: 70,
      before_score: 0,
      after_score: 70,
      decision_reason: "initial_user_prompt",
      input_signal: "retro outrun racing",
      change_impact: "initial_generation",
      confidence: 0.91,
      error_code: null,
      created_at: minutes(18),
    },
    {
      id: "se-2",
      session_id: "sess-demo-1",
      event_type: "agent_activity",
      agent: "visual_qa",
      action: "evaluate",
      summary: "HUD contrast improved for mobile",
      score: 84,
      before_score: 70,
      after_score: 84,
      decision_reason: "visual_metrics_assessment",
      input_signal: "genre=racing",
      change_impact: "quality_pass",
      confidence: 0.74,
      error_code: null,
      created_at: minutes(12),
    },
    {
      id: "se-3",
      session_id: "sess-demo-1",
      event_type: "publish_success",
      agent: "codegen",
      action: "publish",
      summary: "Published to /play/neon-drift-outrun-chain",
      score: 86,
      before_score: 84,
      after_score: 86,
      decision_reason: "user_requested_publish",
      input_signal: "publish",
      change_impact: "session_published",
      confidence: 1,
      error_code: null,
      created_at: minutes(5),
    },
  ],
  "sess-demo-2": [
    {
      id: "se-4",
      session_id: "sess-demo-2",
      event_type: "agent_activity",
      agent: "playtester",
      action: "test",
      summary: "Boot ok but collision recovery feels harsh",
      score: 62,
      before_score: 74,
      after_score: 68,
      decision_reason: "runtime_boot_and_console_validation",
      input_signal: "html_size=9021",
      change_impact: "runtime_issue_detected",
      confidence: 0.71,
      error_code: "runtime_tuning_needed",
      created_at: minutes(7),
    },
  ],
  "sess-demo-3": [
    {
      id: "se-5",
      session_id: "sess-demo-3",
      event_type: "session_cancelled",
      agent: null,
      action: "cancel",
      summary: "Session cancelled by operator",
      score: 0,
      before_score: 55,
      after_score: 55,
      decision_reason: "operator_requested_cancel",
      input_signal: "cancel",
      change_impact: "future_prompt_blocked",
      confidence: 1,
      error_code: null,
      created_at: minutes(8),
    },
  ],
};

export const PREVIEW_LEADERBOARDS: Record<string, Array<{ id: number; player_name: string; score: number; created_at: string }>> = {
  "neon-drift-outrun-chain": [
    { id: 1, player_name: "NOVA", score: 91234, created_at: minutes(14) },
    { id: 2, player_name: "JET", score: 87420, created_at: minutes(18) },
    { id: 3, player_name: "ARC", score: 82110, created_at: minutes(32) },
  ],
  "skyline-jet-infinite": [
    { id: 4, player_name: "SKY", score: 5520, created_at: minutes(40) },
    { id: 5, player_name: "ACE", score: 4980, created_at: minutes(55) },
  ],
};
